
export const orderTypes = {

    ORDER_CREATE_REQUEST: '[ORDER] ORDER_CREATE_REQUEST',
    ORDER_CREATE_SUCCESS: '[ORDER] ORDER_CREATE_SUCCESS',
    ORDER_CREATE_FAIL: '[ORDER] ORDER_CREATE_FAIL',

    ORDER_DETAILS_REQUEST: '[ORDER] ORDER_DETAILS_REQUEST',
    ORDER_DETAILS_SUCCESS: '[ORDER] ORDER_DETAILS_SUCCESS',
    ORDER_DETAILS_FAIL: '[ORDER] ORDER_DETAILS_FAIL'

}