
export const orderTypes = {

    ORDER_CREATE_REQUEST: '[ORDERS] ORDER_CREATE_REQUEST',
    ORDER_CREATE_SUCCESS: '[ORDERS] ORDER_CREATE_SUCCESS',
    ORDER_CREATE_FAIL: '[ORDERS] ORDER_CREATE_FAIL',
    ORDER_CREATE_RESET: '[ORDERS] ORDER_CREATE_RESET',

    ORDER_DETAILS_REQUEST: '[ORDERS] ORDER_DETAILS_REQUEST',
    ORDER_DETAILS_SUCCESS: '[ORDERS] ORDER_DETAILS_SUCCESS',
    ORDER_DETAILS_FAIL: '[ORDERS] ORDER_DETAILS_FAIL',

    ORDER_PAY_REQUEST : '[ORDERS] ORDER_PAY_REQUEST',
    ORDER_PAY_SUCCESS : '[ORDERS] ORDER_PAY_SUCCESS',
    ORDER_PAY_FAIL : '[ORDERS] ORDER_PAY_FAIL',
    ORDER_PAY_RESET : '[ORDERS] ORDER_PAY_RESET',

    ORDER_LIST_MY_ORDERS_REQUEST : '[ORDERS] ORDER_LIST_MY_ORDERS_REQUEST',
    ORDER_LIST_MY_ORDERS_SUCCESS : '[ORDERS] ORDER_LIST_MY_ORDERS_SUCCESS',
    ORDER_LIST_MY_ORDERS_FAIL : '[ORDERS] ORDER_LIST_MY_ORDERS_FAIL',
    ORDER_LIST_MY_ORDERS_RESET : '[ORDERS] ORDER_LIST_MY_ORDERS_RESET',

    ORDER_LIST_REQUEST : '[ORDERS] ORDER_LIST_REQUEST',
    ORDER_LIST_SUCCESS : '[ORDERS] ORDER_LIST_SUCCESS',
    ORDER_LIST_FAIL : '[ORDERS] ORDER_LIST_FAIL',
    ORDER_LIST_RESET : '[ORDERS] ORDER_LIST_MY_ORDERS_RESET',

}