
export const orderTypes = {

    ORDER_CREATE_REQUEST: '[ORDER] ORDER_CREATE_REQUEST',
    ORDER_CREATE_SUCCESS: '[ORDER] ORDER_CREATE_SUCCESS',
    ORDER_CREATE_FAIL: '[ORDER] ORDER_CREATE_FAIL',

    ORDER_DETAILS_REQUEST: '[ORDER] ORDER_DETAILS_REQUEST',
    ORDER_DETAILS_SUCCESS: '[ORDER] ORDER_DETAILS_SUCCESS',
    ORDER_DETAILS_FAIL: '[ORDER] ORDER_DETAILS_FAIL',

    ORDER_PAY_REQUEST : '[ORDER] ORDER_PAY_REQUEST',
    ORDER_PAY_SUCCESS : '[ORDER] ORDER_PAY_SUCCESS',
    ORDER_PAY_FAIL : '[ORDER] ORDER_PAY_FAIL',
    ORDER_PAY_RESET : '[ORDER] ORDER_PAY_RESET',

    ORDER_LIST_MY_ORDERS_REQUEST : '[ORDER] ORDER_LIST_MY_ORDERS_REQUEST',
    ORDER_LIST_MY_ORDERS_SUCCESS : '[ORDER] ORDER_LIST_MY_ORDERS_SUCCESS',
    ORDER_LIST_MY_ORDERS_FAIL : '[ORDER] ORDER_LIST_MY_ORDERS_FAIL',
    ORDER_LIST_MY_ORDERS_RESET : '[ORDER] ORDER_LIST_MY_ORDERS_RESET',
}