
export const productTypes = {

    PRODUCT_LIST_REQUEST: '[PRODUCTS] PRODUCT_LIST_REQUEST',
    PRODUCT_LIST_SUCCESS: '[PRODUCTS] PRODUCT_LIST_SUCCESS',
    PRODUCT_LIST_FAIL: '[PRODUCTS] PRODUCT_LIST_FAIL',

    PRODUCT_DETAILS_REQUEST: '[PRODUCTS] PRODUCT_DETAILS_REQUEST',
    PRODUCT_DETAILS_SUCCESS: '[PRODUCTS] PRODUCT_DETAILS_SUCCESS',
    PRODUCT_DETAILS_FAIL: '[PRODUCTS] PRODUCT_DETAILS_FAIL',

}