
export const productTypes = {

    PRODUCT_LIST_REQUEST: '[PRODUCTS] PRODUCT_LIST_REQUEST',
    PRODUCT_LIST_SUCCESS: '[PRODUCTS] PRODUCT_LIST_SUCCESS',
    PRODUCT_LIST_FAIL: '[PRODUCTS] PRODUCT_LIST_FAIL',

    PRODUCT_DETAILS_REQUEST: '[PRODUCTS] PRODUCT_DETAILS_REQUEST',
    PRODUCT_DETAILS_SUCCESS: '[PRODUCTS] PRODUCT_DETAILS_SUCCESS',
    PRODUCT_DETAILS_FAIL: '[PRODUCTS] PRODUCT_DETAILS_FAIL',

    PRODUCT_DELETE_REQUEST: '[PRODUCTS] PRODUCT_DELETE_REQUEST',
    PRODUCT_DELETE_SUCCESS: '[PRODUCTS] PRODUCT_DELETE_SUCCESS',
    PRODUCT_DELETE_FAIL: '[PRODUCTS] PRODUCT_DELETE_FAIL',

    PRODUCT_CREATE_REQUEST: '[PRODUCTS] PRODUCT_CREATE_REQUEST',
    PRODUCT_CREATE_SUCCESS: '[PRODUCTS] PRODUCT_CREATE_SUCCESS',
    PRODUCT_CREATE_FAIL: '[PRODUCTS] PRODUCT_CREATE_FAIL',

}