
export const userTypes = {

    USER_LOGIN_REQUEST: '[USERS] USER_LOGIN_REQUEST',
    USER_LOGIN_SUCCESS: '[USERS] USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: '[USERS] USER_LOGIN_FAIL',
    USER_LOGIN_LOGOUT: '[USERS] USER_LOGIN_LOGOUT',

    USER_REGISTER_REQUEST: '[USERS] USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS: '[USERS] USER_REGISTER_SUCCESS',
    USER_REGISTER_FAIL: '[USERS] USER_REGISTER_FAIL',
    USER_REGISTER_LOGOUT: '[USERS] USER_REGISTER_LOGOUT',

    USER_DETAILS_REQUEST: '[USERS] USER_DETAILS_REQUEST',
    USER_DETAILS_SUCCESS: '[USERS] USER_DETAILS_SUCCESS',
    USER_DETAILS_FAIL: '[USERS] USER_DETAILS_FAIL',
    USER_DETAILS_LOGOUT: '[USERS] USER_DETAILS_LOGOUT',


}