
export const userTypes = {

    USER_LOGIN_REQUEST: '[USERS] USER_LOGIN_REQUEST',
    USER_LOGIN_SUCCESS: '[USERS] USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: '[USERS] USER_LOGIN_FAIL',
    USER_LOGOUT: '[USERS] USER_LOGOUT',

    USER_REGISTER_REQUEST: '[USERS] USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS: '[USERS] USER_REGISTER_SUCCESS',
    USER_REGISTER_FAIL: '[USERS] USER_REGISTER_FAIL',

    USER_DETAILS_REQUEST: '[USERS] USER_DETAILS_REQUEST',
    USER_DETAILS_SUCCESS: '[USERS] USER_DETAILS_SUCCESS',
    USER_DETAILS_FAIL: '[USERS] USER_DETAILS_FAIL',
    USER_DETAILS_RESET: '[USERS] USER_DETAILS_RESET',

    USER_UPDATE_PROFILE_REQUEST: '[USERS] USER_UPDATE_PROFILE_REQUEST',
    USER_UPDATE_PROFILE_SUCCESS: '[USERS] USER_UPDATE_PROFILE_SUCCESS',
    USER_UPDATE_PROFILE_FAIL: '[USERS] USER_UPDATE_PROFILE_FAIL',
    USER_UPDATE_PROFILE_RESET: '[USERS] USER_UPDATE_PROFILE_RESET',


}