
export const types = {

    PRODUCT_LIST_REQUEST: '[PRODUCTS] PRODUCT_LIST_REQUEST',
    PRODUCT_LIST_SUCCESS: '[PRODUCTS] PRODUCT_LIST_SUCCESS',
    PRODUCT_LIST_FAIL: '[PRODUCTS] PRODUCT_LIST_FAIL',

}