
export const userTypes = {

    USER_LOGIN_REQUEST: '[USERS] USER_LOGIN_REQUEST',
    USER_LOGIN_SUCCESS: '[USERS] USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: '[USERS] USER_LOGIN_FAIL',
    USER_LOGIN_LOGOUT: '[USERS] USER_LOGIN_LOGOUT',


}